# cd back
alias ..='cd ..'

# Home
alias ~='cd ~'

# Projects
alias projects='cd ~/Projects'

# Ls Aliases
alias lsd='ls -lh | grep "^d"'
alias lsf='ls -lh | grep "^-"'
alias lsa='ls -lahF ${colorflag}'
