# Exbibe o prompt
PROMPT_COMMAND=prompt

# Carrega os arquivos de ambiente
source ~/.profile_aliases
source ~/.profile_functions
source ~/.profile_envvars
if [ -e ~/.profile_custom ]; then
	source ~/.profile_custom
fi